### DISCUSSION TITLE
Why Open telemetry metrics are not getting exported to console and OTLP in .net core API ?

### DISCUSSION THREAD

**Discussion by manu-balakrishnan** [open-telemetry/opentelemetry-dotnet#3121] [Q&A]
Open telemetry metrics are not getting exported to console and OTLP in .net core API. here is my configurations.

### **Startup.cs**
```
var serviceName = "SampleAPI.Metrics";

services.AddOpenTelemetryMetrics((builder) =>
{
    builder
    .AddMeter(serviceName)
    .AddConsoleExporter()
    .AddOtlpExporter(options => {
        options.Endpoint = new Uri("http://localhost:4317");
    });
});

```
### **docker-compose**

```
version: "2"
services:


  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./output:/etc/output:rw # Store the logs
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "4317:4317"   # OTLP gRPC receiver
    depends_on:
      - jaeger-all-in-one
      - prometheus
      
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

```
### **otel-collector-config**

```
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  jaeger:
    endpoint: jaeger-all-in-one:14250
    insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
      processors: [batch]

```
### **Prometheus**

```
scrape_configs:
- job_name: 'otel-collector'
  scrape_interval: 10s
  static_configs:
  - targets: ['otel-collector:8889']
  - targets: ['otel-collector:8888']

```
I have added few counters and incremented its value in one of the controller.  however while triggering the API, metrics are not getting exported to neither console nor OTLP. Please help to resolve the issue.
