### DISCUSSION TITLE
TLS Config for OTLP Grpc Exporter

### DISCUSSION THREAD

**Discussion by triciamesina** [open-telemetry/opentelemetry-dotnet#3791] [Q&A]
I am looking to send our application traces directly to a Grpc collector gateway without using a collector agent in my local machine. Is there a way we can configure the [OTLP Grpc Exporter](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Exporter.OpenTelemetryProtocol) using the same configs in the [OpenTelemetry Collector](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/otlpexporter/README.md) ? Specifically the [TLS Configuration Settings](https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configtls/README.md) in the collector.
I have looked in the OtlpExporterOptions but I don't see any TLS related options available.

**Comment by DenisGorchakov** [comment]
Hello everyone!
I ran into a similar issue when trying to enable TLS when transferring metrics from my .NET application to a remote opentelemetry-collector. Without using TLS, the data is transferred correctly, but if I add certificates to the receiver settings, the collector no longer receives the data.
Here is code I use:
.NET app
```
var meterProvider = Sdk.CreateMeterProviderBuilder()
.AddMeter("Metrics")
.AddOtlpExporter((opt, metricReaderOptions) =>
{
    opt.Endpoint = new Uri(ProductManager.ReadResource("http://IP_ADDRESS:4317")); // Now I'm trying to configure TLS on my local OpenTelemetry server, but it will be remote in production
    opt.Protocol = OtlpExportProtocol.Grpc; // Tried to change it to HttpProtobuf, but then it doesn't work at all
    opt.ExportProcessorType = ExportProcessorType.Simple;
})
.Build();
```

OpenTelemetry Collector receiver configuration:
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
		# If uncomment part below, the telemetry is not coming from the app
        #tls:
          #client_ca_file: ca-key.pem
          #cert_file: cert.pem
          #key_file: cert-key.pem
```

Experts, advice please, is it possible to organize Server-Side or mutual TLS to transfer metrics from a .NET app to a remote opentelemetry-collector?
