### ISSUE TITLE
OpenTelemetry collector export to Prometheus is not working

### ISSUE THREAD

**Issue by jojopeter** [open-telemetry/opentelemetry-dotnet#1674]
Team,

I am trying to export the metrics from a .Net application to Prometheus. I am using OTLP Exporter in the application and running OpenTelemetry Collector as a windows service on same system.

**Environment : Windows 10
Collector MSI installed : otel-collector-0.17.0-amd64**

I tried to run collector from console and see the traces are logged but no metrics seen. Attaching my Collector config here for reference.

Any help on this will be greatly appreciated.

```
extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
      http:

  opencensus:

  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

  zipkin:

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: [ '0.0.0.0:8888' ]

processors:
  batch:

exporters:
  zipkin:
    endpoint: "http://127.0.0.1:9411/api/v2/spans"
  prometheus:
    endpoint: "0.0.0.0:8889"
  logging:
    logLevel: debug

service:

  pipelines:

    traces:
      receivers: [otlp, opencensus, jaeger, zipkin]
      processors: [batch]
      exporters: [logging, zipkin]

    metrics:
      receivers: [otlp, opencensus, prometheus]
      processors: [batch]
      exporters: [logging, prometheus]

  extensions: [health_check, pprof, zpages]
```
