### ISSUE TITLE
How to get a simple use case up and running

### ISSUE THREAD

**Issue by msallin** [open-telemetry/opentelemetry-dotnet#1838]
# Question

I try to send my traces to Jaeger but it doesn't work and I don't know how to figure out why.

**Describe your environment.**

My ASP.NET 5.0 runs in a container, beside the Jaeger all-in-one container.
Both are started with the same docker-compose.

Jaeger starts and the UI is accessible. My application starts as well but the Jaeger UI remains empty.
I turned on all CLR exceptions in the debugger but all seems fine.
How can I see if the application was able to send traces to Jaeger? Is there any logging which I can turn on?

```
            services.AddOpenTelemetryTracing(builder => builder
                .SetSampler(new AlwaysOnSampler())
                .AddSource("EFCore.BulkExtensions")
                .AddAspNetCoreInstrumentation()
                .AddHttpClientInstrumentation()
                .AddSqlClientInstrumentation()
                .AddJaegerExporter(exporterOptions =>
                {
                    exporterOptions.AgentHost = "jaeger";
                    exporterOptions.AgentPort = 6831;
                    exporterOptions.ExportProcessorType = ExportProcessorType.Simple;
                }));

```

```
  jaeger:
    image: jaegertracing/all-in-one
    ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
        - "16686:16686"
        - "14268:14268"
        - "9411:9411"
```
