### ISSUE TITLE
using otlp http endpoints not grpc 

### ISSUE THREAD

**Issue by skadefro** [open-telemetry/opentelemetry-dotnet#1870]
# Question
When using nodejs ( for instance the [collector-exporter-node](https://github.com/open-telemetry/opentelemetry-js/tree/1eed360e4e151854a7feaf253350e510201e6dcc/examples/collector-exporter-node) we can use @opentelemetry/exporter-collector to talk to the http endpoints and @opentelemetry/exporter-collector-grpc to talk using otlp/grpc ... Unfortunately I cannot use grpc, and was looking for a way to use opentelemetry-dotnet with the same http endpoints. If I search though the codebase for the endpoints, ( /v1/metrics and /v1/trace ) i find 4 hits, all in "OpenTelemetry.Exporter.OpenTelemetryProtocol" but I cannot find any good documentation on how to use it.
**Describe your environment.**
C# / .net 4.6.2 talking to otel/opentelemetry-collector running in on kubernetes
otel-collector-config
```
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          http:
            cors_allowed_origins:
            - http://*
            - https://*
```

**What are you trying to achieve?**
Use opentelemetry-dotnet with otel/opentelemetry-collector using http endpoints and not grpc
