### ISSUE TITLE
OTLP exporter not working with netcoreapp3.1

### ISSUE THREAD

**Issue by dszmigielski** [open-telemetry/opentelemetry-dotnet#2253]
# Bug Report

List of [NuGet packages](https://www.nuget.org/profiles/OpenTelemetry):

* `OpenTelemetry.Exporter.Console 1.2.0-alpha1`
* **`OpenTelemetry.Exporter.OpenTelemetryProtocol 1.2.0-alpha1`**

Runtime version:

* netcoreapp3.1

## Symptom

I have created a very simple application to test OTLP exporter and set up OTEL collector locally. I started with application targeting `net5.0` and it works fine - I can see the spans both in application console (console exporter) as well as logged by the collector. Unfortunately when I change the target to `netcoreapp3.1` I can no longer see the spans appearing on the collector side.

## Reproduce

Application code:

```csharp
using System;
using System.Diagnostics;
using System.Net.Http;
using System.Threading.Tasks;
using OpenTelemetry;
using OpenTelemetry.Trace;

namespace ConsoleApp1
{
    public class Program
    {
        private static readonly ActivitySource ActivitySource = new ActivitySource("ConsoleApp");

        public static async Task Main(string[] args)
        {
            await Execute();
        }

        private static async Task Execute()
        {

            using var tracerProvider = Sdk.CreateTracerProviderBuilder()
                .AddSource("ConsoleApp")
                .AddConsoleExporter()
                .AddOtlpExporter(options =>
                {
                    options.ExportProcessorType = ExportProcessorType.Simple;
                })
                .Build();

            while (true)
            {
                using (var activity = ActivitySource.StartActivity("My Activity"))
                {
                    activity?.AddTag("MyTag", "MyValue");

                    using var client = new HttpClient();
                    var result = await client.GetAsync("http://www.google.com");
                    var content = await result.Content.ReadAsStringAsync();

                    activity?.AddTag("Content-Length", content.Length);
                }

                Console.ReadLine();
            }
        }
    }
}

```

OTEL collector configuration (`otel/opentelemetry-collector:latest` docker image):

```yaml
extensions:
  health_check:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679

receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    logLevel: debug
  jaeger:
    endpoint: jaeger:14250
    insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [logging, jaeger]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [logging]

  extensions: [health_check, pprof, zpages]
```

## Additional Context

I have tried sniffing what's happening on the network and it seems odd as I can see the correct HTTP request being sent and receiving OK responses from the collector (and bad requests when testing with collector not running). Despite that I do not see spans being logged on the collector side. I would think this is the collector issue if not for the `net5.0` working fine.
