### ISSUE TITLE
Using OpenTelemetry Collector with AspNet Core 3.1

### ISSUE THREAD

**Issue by alefcarlos** [open-telemetry/opentelemetry-dotnet#2624]
# How to run the aspnetcore example with otlp ?

**Describe your environment.**

I tried do run the [AspnetCore example  ](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/examples/AspNetCore)with `"UseTracingExporter": "otlp"`, but I could not see any traces

Describe any aspect of your environment relevant to the question.

I used this `docker-compose`

```yaml
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  otel:
    image: otel/opentelemetry-collector-contrib:0.38.0
    container_name: otel
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317"        # OTLP gRPC receiver
      - "55670:55679" # zpages extension
    depends_on:
      - zipkin
      - prometheus
 ```

and this configuration:

```yaml
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"

  prometheus:
    endpoint: "0.0.0.0:8889"

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
```

And the last, on `appsettings.json`

```json
{
  "Otlp": {
    "ServiceName": "otlp-test",
    "Endpoint": "http://localhost:4317"
  }
}
```
**What are you trying to achieve?**

Run AspNetCore with OpenTelemetry collector enabled

What did you expect to see?

See my traces on Zipkin

## Additional Context

Add any other context about the problem here. If you followed an existing
documentation, please share the link to it.

https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/examples/AspNetCore

**Comment by joaopgrassi** [comment]
Not so familiar with the sample, but a quick thing you could try is adding the log exporter in the collector config to see if at least the collector is getting the traces:

```yaml
exporters:
  # Logging exporter in debug level
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin, logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
```
