### ISSUE TITLE
Not receiving metrics  - .NET 6, latest packages

### ISSUE THREAD

**Issue by maranmaran** [open-telemetry/opentelemetry-dotnet#2775]
# Question

Greetings, 

I'm not sure what I'm missing in setting up my OTLP collector and exporting metrics. So maybe someone with good eye can tell me perhaps.

**Traces work**, I'm receiving traces in console and on zipkin just fine.

However, with **metrics** I'm experiencing **issues**, **no console exports** and ends up on metrics endpoint and prometheus gets no relevant data.

**Describe your environment.**
Telemetry collector and Prometheus instance running in docker via docker compose

Posting stripped down manifests to data only relevant to metrics and prometheus

docker-compose.yml
```
services:
  collector:
    container_name: collector
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yml", "--log-level=DEBUG"]
    volumes:
      - ./config/collector-config.yml:/etc/otel-collector-config.yml
    ports:
      # receivers
      - "4317:4317" # OTLP receiver
      # exporters
      - "9464:9464" # Prometheus exporter metrics

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus-config.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
```

collector config
```
receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  otlp:
    endpoint: http://localhost:4317
  prometheus:
    endpoint: "0.0.0.0:9464"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

```

prometheus config 
```
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "collector"
    static_configs:
      - targets: ["collector:9464"]
```

API code

```
services.AddOpenTelemetryMetrics(builder =>
                {
                    builder
                        .AddAspNetCoreInstrumentation()
                        .AddHttpClientInstrumentation()
                        .AddMeter(serviceName)
                        .AddConsoleExporter()
                        .AddOtlpExporter(x =>
                        {
                            x.Endpoint = new Uri(Configuration["http://localhost:4317"]);
                            x.Protocol = OtlpExportProtocol.Grpc;
                        });
                });
```

**What are you trying to achieve?**
Get metrics in my prometheus instance

What did you expect to see?
Metrics in console

What am I missing?
