### ISSUE TITLE
Metrics not sent from an ASP.NET application with RC9

### ISSUE THREAD

**Issue by devpro** [open-telemetry/opentelemetry-dotnet#3078]
# Bug Report

- OpenTelemetry.Exporter.OpenTelemetryProtocol 1.2.0-rc3
- OpenTelemetry.Extensions.Hosting 1.0.0-rc9
- OpenTelemetry.Instrumentation.AspNetCore 1.0.0-rc9

* Runtime net6.0

## Symptom

There is a regression in the latest packages ("RC9"), the metrics are not sent anymore by an ASP.NET application using `AddOpenTelemetryMetrics` extension method.

**What is the expected behavior?**

Metrics should be sent to the exporter defined in `AddOpenTelemetryMetrics` extension method.

OpenTelemetry collector console should display messages like:

```log
otel-collector    | 2022-03-23T10:10:57.968Z    INFO    loggingexporter/logging_exporter.go:54  MetricsExporter {"#metrics": 2}
```

**What is the actual behavior?**

No metrics is sent.

## Reproduce

* Start an OpenTelemetry Collector listening on port 4317

```yaml
#  docker-compose.yml
version: "3.9"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector.yml"]
    volumes:
      - .opentelemetry-collector.yml:/etc/otel-collector.yml
    ports:
      - "4317:4317"

# opentelemetry-collector.yml
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging]
```

* Create a new ASP.NET REST API .NET6 project and add OpenTelemetry packages

```csproj
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.2.0-rc3" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol.Logs" Version="1.0.0-rc9" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc9" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9" />
  </ItemGroup>

</Project>
```

* Update `Progam.cs` file

```csharp
using System.Diagnostics;
using System.Diagnostics.Metrics;
using OpenTelemetry.Metrics;
using OpenTelemetry.Resources;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddOpenTelemetryMetrics(builder =>
{
    builder.SetResourceBuilder(ResourceBuilder.CreateDefault().AddService("MyService"));
    builder.AddAspNetCoreInstrumentation();
    builder.AddMeter("MyApplicationMetrics");
    builder.AddOtlpExporter(options => options.Endpoint = new Uri("http://localhost:4317"));
});

var app = builder.Build();

var activitySource = new ActivitySource("MyApplicationActivitySource");
var meter = new Meter("MyApplicationMetrics");
var requestCounter = meter.CreateCounter<int>("compute_requests");

app.MapGet("/", /*async (ILogger<Program> logger)*/ () =>
{
    requestCounter.Add(1);

    return Results.Ok();
});

app.Run();
```

## Additional Context

Same test is ok with previous versions:

```csproj
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.2.0-beta1" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol.Logs" Version="1.0.0-rc8" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.0.0-rc8" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc8" />
  </ItemGroup>

</Project>
```
