### ISSUE TITLE
Exporting to Zipkin in Docker Compose

### ISSUE THREAD

**Issue by davidkeaveny** [open-telemetry/opentelemetry-dotnet#3752]
I am prototyping an ASP.NET Core 6.0 application that uses OpenTelemetry to publish to Zipkin, with both the app and Zipkin hosted in Docker Compose.

I've installed the following packages:

OpenTelemetry 1.4.0-beta.1
OpenTelemetry.Exporter.Console 1.4.0-beta.1
OpenTelemetry.Exporter.Zipkin 1.4.0-beta.1
OpenTelemetry.Extensions.Hosting 1.0.0-rc9.7
OpenTelemetry.Instrumentation.AspNetCore 1.0.0-rc9.7
OpenTelemetry.Instrumentation.Http 1.0.0-rc9.7
OpenTelemetry.Instrumentation.SqlClient 1.0.0-rc9.7

My docker-compose.yaml looks like this:
```
version: '3.4'

services:

  zipkin:
    image: openzipkin/zipkin-slim
    ports:
      - "5411:9411"

  my-api:
    image: ${DOCKER_REGISTRY-}my-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ZIPKIN_HOST=http://zipkin/api/v2/spans
    depends_on:
      - zipkin
```

and OpenTelemetry is configured in the ASP.NET Core application as:

```
 services.AddOpenTelemetryTracing(builder =>
 {
     builder
         .AddConsoleExporter()
         .AddZipkinExporter(zipkin =>
         {
             zipkin.Endpoint = new Uri(Environment.GetEnvironmentVariable("ZIPKIN_HOST"));
         })
         .AddSource("MyProduct")
         .SetResourceBuilder(
             ResourceBuilder
                 .CreateDefault()
                 .AddService(serviceName: "MyProduct", serviceVersion: "0.0.1"))
         .AddHttpClientInstrumentation()
         .AddAspNetCoreInstrumentation()
         .AddSqlClientInstrumentation();
 });
```

When I run the app, I can see OpenTelemetry activities being written to the console; however, when I connect to Zipkin at `http://localhost:5411/zipkin/`, the UI does not display any activities. Is there some configuration that I am missing when running in Docker?
