### ISSUE TITLE
Is http/json expected to be implemented?

### ISSUE THREAD

**Issue by paulomorgado** [open-telemetry/opentelemetry-dotnet#5764]
### What is the question?

Altough linking to https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md, [OtlpExportProtocol](https://github.com/open-telemetry/opentelemetry-dotnet/blob/57ee852470c6331c6ee023fb46e26858c69136ab/src/OpenTelemetry.Exporter.OpenTelemetryProtocol/OtlpExportProtocol.cs) misses `http/json`.

Is `http/json` exporting to be expected?

**Comment by cijothomas** [comment]
Yes, but no timeline. It is a _MAY_ from the spec.

**Comment by Leonardo-Ferreira** [comment]
any news here? it seems that Datadog only accepts http+json

@cijothomas, that's no longer a MAY: Protocol: `The transport protocol. Options MUST be one of: grpc, http/protobuf, http/json.` [docs](https://opentelemetry.io/docs/specs/otel/protocol/exporter/)

**Comment by cijothomas** [comment]
> any news here? it seems that Datadog only accepts http+json
> 
> [@cijothomas](https://github.com/cijothomas), that's no longer a MAY: Protocol: `The transport protocol. Options MUST be one of: grpc, http/protobuf, http/json.` [docs](https://opentelemetry.io/docs/specs/otel/protocol/exporter/)

Its still a MAY in spec (no changes since this issue was opened)

https://opentelemetry.io/docs/specs/otel/protocol/exporter/#specify-protocol 

> They also MAY support http/json


Irrespective:
1. Nothing preventing an implementation here. Likely just bandwidth issue.
2. Datadog accepts protobuf from their docs: https://docs.datadoghq.com/opentelemetry/setup/otlp_ingest/logs shows http/protobuf

**Comment by Leonardo-Ferreira** [comment]
>Datadog accepts protobuf from their docs: https://docs.datadoghq.com/opentelemetry/setup/otlp_ingest/logs shows http/protobuf

@cijothomas  yes they do it for logs, but not for traces... I have a ticket open with them to guarantee this, but if I send the traces like 
```curl
curl -v -X POST http://10.0.0.1:4318/v1/traces \
-H "Content-Type: application/json" \
-d '{
"resourceSpans": [
    {
    "resource": {
        "attributes": [
        {
            "key": "service.name",
            "value": {
            "stringValue": "utils-otel-testclient"
            }
        },
        {
            "key": "service.version",
            "value": {
            "stringValue": "1.0.0"
            }
        },
        {
            "key": "host.name",
            "value": {
            "stringValue": "localhost"
            }
        }
        ]
    },
    "scopeSpans": [
        {
        "scope": {
            "name": "utils.logging.otel",
            "version": "1.0.0"
        },
        "spans": [
            {
            "traceId": "5b8aa5a2d2c872e8321cf37308d69df2",
            "spanId": "051581bf3cb55c13",
            "parentSpanId": "",
            "name": "AnotherWeatherForecast.Get",
            "kind": "SPAN_KIND_SERVER",
            "startTimeUnixNano": "'$(date +%s%N)'",
            "endTimeUnixNano": "'$(($(date +%s%N) + 100000000))'",
            "attributes": [
                {
                "key": "http.method",
                "value": {
                    "stringValue": "GET"
                }
                },
                {
                "key": "http.route",
                "value": {
                    "stringValue": "/AnotherWeatherForecast"
                }
                },
                {
                "key": "http.status_code",
                "value": {
                    "intValue": 200
                }
                },
                {
                "key": "custom.property",
                "value": {
                    "stringValue": "teste3"
                }
                }
            ],
            "status": {
                "code": "STATUS_CODE_OK"
            },
            "events": [
                {
                "timeUnixNano": "'$(date +%s%N)'",
                "name": "testeInfo",
                "attributes": [
                    {
                    "key": "level",
                    "value": {
                        "stringValue": "Information"
                    }
                    }
                ]
                },
                {
                "timeUnixNano": "'$(date +%s%N)'",
                "name": "testeWarning",
                "attributes": [
                    {
                    "key": "level",
                    "value": {
                        "stringValue": "Warning"
                    }
                    }
                ]
                }
            ]
            }
        ]
        }
    ]
    }
]
}'
```

it works as expected

**Comment by Kielek** [comment]
@Leonardo-Ferreira, maybe you can consider collector https://github.com/open-telemetry/opentelemetry-collector/pull/9276 as the solution? You can export in http/protobuf, and the collector can handle changing wire format+ any other modification you might need. In general, it is the recommended setup.

For now, I doubt that any maintainer/current contributor have capacity to handle this request.

@zacharycmontoya, you might be interested in this request.

**Comment by Leonardo-Ferreira** [comment]
hey @Kielek, thanks for the info but ill need a bit more, im not "putting it all together"...

you see, today I use `otel/opentelemetry-collector-contrib:0.77.0` as the collector. I also use the values DD docs recommended:
```yaml
    service:
      # This will make the collector output logs in JSON format
      telemetry:
        logs:
          encoding: "json"
          initial_fields:
            # Add the service field to every log line. It can be used for filtering in Datadog.
            service: "otel-collector"
      pipelines:
        metrics:
          receivers: [hostmetrics, otlp]
          processors: [resourcedetection, k8sattributes]
          exporters: [datadog]
        traces:
          receivers: [otlp]
          processors: [resourcedetection, k8sattributes]
          exporters: [datadog]
        logs:
          receivers: [filelog, otlp]
          exporters: [datadog]
```

now, what am I supposed to do?

**Comment by Kielek** [comment]
Update collector to newer version including changes from https://github.com/open-telemetry/opentelemetry-collector/pull/9276/files#diff-1c819654ca0bdd4beeaf16eb0e15dcb3b7d489912f56e1c186f3e697f0c33903

and add otlphttp exporter with json.

Linked changes to the documentation should help.

**Comment by Leonardo-Ferreira** [comment]
currently my export config is:
```yml
    exporters:
      datadog:
        api:
          key: "myKeyHere"
          site: datadoghq.com # Change this to your site if not using the default
        sending_queue:
```
so it should be?:
```yml
    exporters:
      datadog:
        api:
          key: "myKeyHere"
          site: datadoghq.com # Change this to your site if not using the default
        sending_queue:
      otlphttp:
        endpoint: "https://datadoghq.com"
        encoding: "json"
        compression: "none"
        headers:
          x-datadog-api-key: "myKeyHere"
```
