### ISSUE TITLE
Unable to export traces to Jaeger .NET 7

### ISSUE THREAD

**Issue by officialgio** [open-telemetry/opentelemetry-dotnet#5998]
### Package

OpenTelemetry

### Package Version

| Package Name                          | Version |
| ------------------------------------- | ------- |
| OpenTelemetry                    | 1.6.0   |
| OpenTelemetry.Exporter.Jaeger                         | 1.5.1   |
| OpenTelemetry.Extensions.Hosting                                   | 1.6.0     |
| OpenTelemetry.Exporter.Console                                   | 1.6.0     |
| OpenTelemetry.Exporter.OpenTelemetryProtocol                                   | 1.6.0     |
| OpenTelemetry.Instrumentation.AspNetCore                                   | 1.6.0     |
| OpenTelemetry.Instrumentation.Http                                   | 1.6.0     |

### Runtime Version

net7.0

## Description
I'm trying to export my service traces to Jaeger locally. Currently, I'm running my Jaeger docker container and my service locally on port `5007`. 

## What I've Done So Far
* Doubled checked container ports via `.yml` and `docker ps`
* Exported my traces to console successfully.
* I've used older packages to see if it will work, not much luck.
* I've used `AddOtlpExporter` but still unable to get them to show up, I'm not sure If I'm doing the `AddOtlpExporter` correctly.
* I've been trying to look further into the docs but I'm still unable to solve this issue. 

## Expected
I'm trying to hit HTTP request locally to my service in the hopes to see traces show up via: `localhost:16686`

### Actual Result

No traces were exported.

### Additional Context

Here are code snippets: 

Startup.cs: 
```csharp 
// Telemetry Tracing
var serviceSettings = Configuration.GetSection(nameof(ServiceSettings)).Get<ServiceSettings>();

services.AddOpenTelemetry()
    .WithTracing(tracing => tracing
        .SetResourceBuilder(ResourceBuilder.CreateDefault()
            .AddService(serviceName: serviceSettings.ServiceName))
        .AddSource(serviceSettings.ServiceName)
        .AddSource("MassTransit") // Replace with your service name
        .AddAspNetCoreInstrumentation()
        .AddHttpClientInstrumentation()
        .AddJaegerExporter(options =>
        {
            options.AgentHost = "localhost"; // Jaeger Agent hostname
            options.AgentPort = 6831; // Default Jaeger Agent port
        }));
```

docker-compose:
```yml
version: "3.8"

services:
  # ...

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 14250:14250
      - 14268:14268
      - 16686:16686 # to access jaeger UI

volumes:
  # ...
```

![image](https://github.com/user-attachments/assets/caa435e3-bbcd-4176-93ce-8bfa42e99b76)

**Comment by TimothyMothra** [comment]
Hi @officialgio, 
.NET 7 is out of support since May 2024, and the `OpenTelemetry.Exporter.Jaeger` has also been deprecated. I don't think anyone here would be able to provide support for either of those.

Here's some information about using the OpenTelemetryProtocol exporter with Jaeger:
- https://www.jaegertracing.io/docs/1.48/apis/#opentelemetry-protocol-stable
- https://github.com/open-telemetry/opentelemetry-dotnet/tree/e330e57b04fa3e51fe5d63b52bfff891fb5b7961/docs/trace/getting-started-jaeger

**Comment by officialgio** [comment]
Thank you for the reply, I've taken a look into the docs and the available samples. I've added the new code without using `OpenTelemetry.Exporter.Jaeger` as it is no longer in support. The samples and docs state to use `AddOtlpExporter`, but I'm still facing the same issue. 

Code Snippet:

```cs 
// Telemetry Tracing
var serviceSettings = Configuration.GetSection(nameof(ServiceSettings)).Get<ServiceSettings>();

services
    .AddOpenTelemetry()
    .ConfigureResource(resource => resource.AddService(serviceName: serviceSettings.ServiceName))
    .WithTracing(tracing => tracing
        .AddSource(serviceSettings.ServiceName)
        .AddSource("MassTransit")
        .AddHttpClientInstrumentation()
        .AddAspNetCoreInstrumentation()
        .AddOtlpExporter()
    );
```

After running the system locally and hit a POST the traces are visible through console but aren't exported to Jaeger which by default it will do according to this [doc](https://github.com/open-telemetry/opentelemetry-dotnet/tree/e330e57b04fa3e51fe5d63b52bfff891fb5b7961/docs/trace/getting-started-jaeger). 

This is the docker image I am using: 
```yml
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 14250:14250
      - 14268:14268
      - 4317:4317
      - 16686:16686 # to access jaeger UI
```
